# Generated by Django 3.2.6 on 2021-08-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
