# Generated by Django 3.2.6 on 2021-08-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(max_length=11),
        ),
    ]
