# Generated by Django 3.2.6 on 2021-08-25 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cashbackresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackresponse',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
    ]
