# Generated by Django 3.2.6 on 2021-08-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adress',
            new_name='address',
        ),
    ]
